In [1]:
import cv2


img = cv2.imread('img/apple.jpg', 0)
# img, contours, hierarchy = cv2.findContours(img, cv2.cv2.RETR_TREE, cv2.CHAIN_APPROX_TC89_KCOS)


In [28]:
# cv2.drawContours(img, [countrs], -1, (0,255,0), 3)

TypeError: contours is not a numerical tuple

In [31]:
cv2.imwrite('img/apple-count.jpg', img)

True

In [1]:
%%time
from scipy.ndimage import label, find_objects
import cv2 
import numpy as np
from img_preperation import img_quantize, img_blur, read_img
from spline import Spline
from outline import get_outline_points
from SVGBuilder import SVGBuilder


img = cv2.imread('img/apple.jpg')
img = img_blur(img)
img = img_quantize(img, 7)
img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

svg = SVGBuilder()

for color in np.unique(img):
    img[img!=color] = 0
    matrix, count = label(img)

    matrix[matrix!=0] = 255
    matrix = matrix.astype('uint8')

# show_img(matrix.astype('uint8'))

    countrs, _ = cv2.findContours(matrix, cv2.cv2.RETR_TREE, cv2.CHAIN_APPROX_TC89_KCOS)
    
    for i in range(len(countrs)):    
        outline_on_matrix = list(zip(countrs[i].T[0][0], countrs[i].T[1][0]))
        #countrs[0], countrs[1], countrs[2] и т.д.
        outline_on_img = Spline.get_cubic_b_spline_points(np.array(outline_on_matrix))

        fill = f"rgb({','.join(map(str, color))})"
        
        svg.add_spline_element(outline_on_img, fill)

svg.save_as_svg('vot-eto-new.svg')

[ 98 108 116 148 153 187 253]


ValueError: too many values to unpack (expected 2)

In [40]:
def show_img(frame):
    print(frame)
    cv2.imshow('image', frame)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [24]:
%%time
from copy import deepcopy

# В чем идея
# img[img!=255] = 0, вот так можно создать маску нужную мне
# мы оставляем 1 какой-то цвет, например 255, а все остальные убираем
# потом мы можем использовать scipy.ndimage.label, который среди 2ух цветов, находит уникальные группы
# потом по возращаемой матрице, мы можем найти объекты, вполне конкретные слайсы
# сложность алгоритма сильно упадет, потому что не надо будет искать все 255 цветов, а только заданное пользователем

for x in np.unique(img):
    img_test = deepcopy(img)
    img_test[img_test!=x] = 0
    matrix, count = label(img_test)
    print(count)
    find_objects(matrix)

4
1
59
2
22
13
1
CPU times: user 36.8 ms, sys: 0 ns, total: 36.8 ms
Wall time: 33.7 ms


In [84]:
matrix.astype('uint8')

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [88]:
pip freeze

absl-py==0.9.0
aiohttp==3.6.2
amqp==2.5.2
asn1crypto==0.24.0
astroid==2.3.3
astunparse==1.6.3
async-timeout==3.0.1
attrs==19.1.0
backcall==0.1.0
beautifulsoup4==4.8.0
billiard==3.6.3.0
bleach==3.1.0
bs4==0.0.1
cachetools==3.1.1
cairocffi==1.1.0
CairoSVG==2.4.2
celery==4.4.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
clarifai==2.6.2
click==7.1.2
cloudpickle==1.4.1
conda==4.3.16
configparser==4.0.2
cryptography==2.9.2
cssselect==1.0.3
cssselect2==0.2.2
cycler==0.10.0
Cython==0.29.14
DAWG-Python==0.7.2
decorator==4.4.2
defusedxml==0.6.0
detectron2==0.1.1+cpu
Django==2.2.3
django-admin-json-editor==0.2.0
django-jsoneditor==0.1.6
docopt==0.6.2
EasyProcess==0.2.7
emoji==0.5.4
entrypoints==0.3
environ==1.0
et-xmlfile==1.0.1
fire==0.2.1
Flask==1.1.2
future==0.17.1
fvcore==0.1.1.post20200617
gast==0.3.3
google-api-core==1.16.0
google-api-python-client==1.7.11
google-auth==1.12.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-cloud-core==1.3.0
google-cloud-storage==1.26.0
goo

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8)

In [68]:
img

array([[253, 253, 253, ..., 253, 253, 253],
       [253, 253, 253, ..., 253, 253, 253],
       [253, 253, 253, ..., 253, 253, 253],
       ...,
       [253, 253, 253, ..., 253, 253, 253],
       [253, 253, 253, ..., 253, 253, 253],
       [253, 253, 253, ..., 253, 253, 253]], dtype=uint8)